/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PropertyPrice {
  'month' : YearMonth,
  'changeFromPrevMonth' : bigint,
  'propertyType' : PropertyType,
  'averagePrice' : bigint,
  'pricePerSqm' : bigint,
  'regionId' : RegionId,
  'changePercent' : bigint,
}
export type PropertyType = { 'villa' : null } |
  { 'land' : null } |
  { 'apartment' : null };
export interface Region {
  'id' : RegionId,
  'name' : string,
  'level' : RegionLevel,
  'parentId' : [] | [RegionId],
}
export type RegionId = bigint;
export type RegionLevel = { 'province' : null } |
  { 'city' : null } |
  { 'district' : null };
export interface RegionSummary {
  'region' : Region,
  'latestPrice' : [] | [PropertyPrice],
}
export type YearMonth = string;
export interface _SERVICE {
  'addPropertyPrice' : ActorMethod<[PropertyPrice], undefined>,
  'addRegion' : ActorMethod<[Region], RegionId>,
  'compareRegions' : ActorMethod<
    [Array<RegionId>, PropertyType],
    Array<PropertyPrice>
  >,
  'getLastUpdated' : ActorMethod<[], bigint>,
  'getRegionPrices' : ActorMethod<
    [RegionId, PropertyType, bigint],
    Array<PropertyPrice>
  >,
  'getRegionSummaries' : ActorMethod<[PropertyType], Array<RegionSummary>>,
  'getRegions' : ActorMethod<[[] | [RegionId]], Array<Region>>,
  'initSampleData' : ActorMethod<[], undefined>,
  'refreshPrices' : ActorMethod<[], undefined>,
  'searchRegions' : ActorMethod<[string], Array<Region>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];