/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const YearMonth = IDL.Text;
export const PropertyType = IDL.Variant({
  'villa' : IDL.Null,
  'land' : IDL.Null,
  'apartment' : IDL.Null,
});
export const RegionId = IDL.Nat;
export const PropertyPrice = IDL.Record({
  'month' : YearMonth,
  'changeFromPrevMonth' : IDL.Int,
  'propertyType' : PropertyType,
  'averagePrice' : IDL.Nat,
  'pricePerSqm' : IDL.Nat,
  'regionId' : RegionId,
  'changePercent' : IDL.Int,
});
export const RegionLevel = IDL.Variant({
  'province' : IDL.Null,
  'city' : IDL.Null,
  'district' : IDL.Null,
});
export const Region = IDL.Record({
  'id' : RegionId,
  'name' : IDL.Text,
  'level' : RegionLevel,
  'parentId' : IDL.Opt(RegionId),
});
export const RegionSummary = IDL.Record({
  'region' : Region,
  'latestPrice' : IDL.Opt(PropertyPrice),
});

export const idlService = IDL.Service({
  'addPropertyPrice' : IDL.Func([PropertyPrice], [], []),
  'addRegion' : IDL.Func([Region], [RegionId], []),
  'compareRegions' : IDL.Func(
      [IDL.Vec(RegionId), PropertyType],
      [IDL.Vec(PropertyPrice)],
      ['query'],
    ),
  'getLastUpdated' : IDL.Func([], [IDL.Int], ['query']),
  'getRegionPrices' : IDL.Func(
      [RegionId, PropertyType, IDL.Nat],
      [IDL.Vec(PropertyPrice)],
      ['query'],
    ),
  'getRegionSummaries' : IDL.Func(
      [PropertyType],
      [IDL.Vec(RegionSummary)],
      ['query'],
    ),
  'getRegions' : IDL.Func([IDL.Opt(RegionId)], [IDL.Vec(Region)], ['query']),
  'initSampleData' : IDL.Func([], [], []),
  'refreshPrices' : IDL.Func([], [], []),
  'searchRegions' : IDL.Func([IDL.Text], [IDL.Vec(Region)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const YearMonth = IDL.Text;
  const PropertyType = IDL.Variant({
    'villa' : IDL.Null,
    'land' : IDL.Null,
    'apartment' : IDL.Null,
  });
  const RegionId = IDL.Nat;
  const PropertyPrice = IDL.Record({
    'month' : YearMonth,
    'changeFromPrevMonth' : IDL.Int,
    'propertyType' : PropertyType,
    'averagePrice' : IDL.Nat,
    'pricePerSqm' : IDL.Nat,
    'regionId' : RegionId,
    'changePercent' : IDL.Int,
  });
  const RegionLevel = IDL.Variant({
    'province' : IDL.Null,
    'city' : IDL.Null,
    'district' : IDL.Null,
  });
  const Region = IDL.Record({
    'id' : RegionId,
    'name' : IDL.Text,
    'level' : RegionLevel,
    'parentId' : IDL.Opt(RegionId),
  });
  const RegionSummary = IDL.Record({
    'region' : Region,
    'latestPrice' : IDL.Opt(PropertyPrice),
  });
  
  return IDL.Service({
    'addPropertyPrice' : IDL.Func([PropertyPrice], [], []),
    'addRegion' : IDL.Func([Region], [RegionId], []),
    'compareRegions' : IDL.Func(
        [IDL.Vec(RegionId), PropertyType],
        [IDL.Vec(PropertyPrice)],
        ['query'],
      ),
    'getLastUpdated' : IDL.Func([], [IDL.Int], ['query']),
    'getRegionPrices' : IDL.Func(
        [RegionId, PropertyType, IDL.Nat],
        [IDL.Vec(PropertyPrice)],
        ['query'],
      ),
    'getRegionSummaries' : IDL.Func(
        [PropertyType],
        [IDL.Vec(RegionSummary)],
        ['query'],
      ),
    'getRegions' : IDL.Func([IDL.Opt(RegionId)], [IDL.Vec(Region)], ['query']),
    'initSampleData' : IDL.Func([], [], []),
    'refreshPrices' : IDL.Func([], [], []),
    'searchRegions' : IDL.Func([IDL.Text], [IDL.Vec(Region)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };