/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RegionSummary {
    region: Region;
    latestPrice?: PropertyPrice;
}
export interface PropertyPrice {
    month: YearMonth;
    changeFromPrevMonth: bigint;
    propertyType: PropertyType;
    averagePrice: bigint;
    pricePerSqm: bigint;
    regionId: RegionId;
    changePercent: bigint;
}
export type RegionId = bigint;
export type YearMonth = string;
export interface Region {
    id: RegionId;
    name: string;
    level: RegionLevel;
    parentId?: RegionId;
}
export enum PropertyType {
    villa = "villa",
    land = "land",
    apartment = "apartment"
}
export enum RegionLevel {
    province = "province",
    city = "city",
    district = "district"
}
export interface backendInterface {
    addPropertyPrice(price: PropertyPrice): Promise<void>;
    addRegion(region: Region): Promise<RegionId>;
    compareRegions(regionIds: Array<RegionId>, propertyType: PropertyType): Promise<Array<PropertyPrice>>;
    getLastUpdated(): Promise<bigint>;
    getRegionPrices(regionId: RegionId, propertyType: PropertyType, months: bigint): Promise<Array<PropertyPrice>>;
    getRegionSummaries(propertyType: PropertyType): Promise<Array<RegionSummary>>;
    getRegions(parentId: RegionId | null): Promise<Array<Region>>;
    initSampleData(): Promise<void>;
    refreshPrices(): Promise<void>;
    searchRegions(queryText: string): Promise<Array<Region>>;
}
import type { PropertyPrice as _PropertyPrice, PropertyType as _PropertyType, Region as _Region, RegionId as _RegionId, RegionLevel as _RegionLevel, RegionSummary as _RegionSummary, YearMonth as _YearMonth } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addPropertyPrice(arg0: PropertyPrice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPropertyPrice(to_candid_PropertyPrice_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPropertyPrice(to_candid_PropertyPrice_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addRegion(arg0: Region): Promise<RegionId> {
        if (this.processError) {
            try {
                const result = await this.actor.addRegion(to_candid_Region_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRegion(to_candid_Region_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async compareRegions(arg0: Array<RegionId>, arg1: PropertyType): Promise<Array<PropertyPrice>> {
        if (this.processError) {
            try {
                const result = await this.actor.compareRegions(arg0, to_candid_PropertyType_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.compareRegions(arg0, to_candid_PropertyType_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLastUpdated(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastUpdated();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastUpdated();
            return result;
        }
    }
    async getRegionPrices(arg0: RegionId, arg1: PropertyType, arg2: bigint): Promise<Array<PropertyPrice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegionPrices(arg0, to_candid_PropertyType_n3(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegionPrices(arg0, to_candid_PropertyType_n3(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegionSummaries(arg0: PropertyType): Promise<Array<RegionSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegionSummaries(to_candid_PropertyType_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegionSummaries(to_candid_PropertyType_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegions(arg0: RegionId | null): Promise<Array<Region>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegions(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegions(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async initSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSampleData();
            return result;
        }
    }
    async refreshPrices(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshPrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshPrices();
            return result;
        }
    }
    async searchRegions(arg0: string): Promise<Array<Region>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchRegions(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchRegions(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_PropertyPrice_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyPrice): PropertyPrice {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_RegionLevel_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegionLevel): RegionLevel {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_RegionSummary_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegionSummary): RegionSummary {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Region_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Region): Region {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RegionId]): RegionId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PropertyPrice]): PropertyPrice | null {
    return value.length === 0 ? null : from_candid_PropertyPrice_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    month: _YearMonth;
    changeFromPrevMonth: bigint;
    propertyType: _PropertyType;
    averagePrice: bigint;
    pricePerSqm: bigint;
    regionId: _RegionId;
    changePercent: bigint;
}): {
    month: YearMonth;
    changeFromPrevMonth: bigint;
    propertyType: PropertyType;
    averagePrice: bigint;
    pricePerSqm: bigint;
    regionId: RegionId;
    changePercent: bigint;
} {
    return {
        month: value.month,
        changeFromPrevMonth: value.changeFromPrevMonth,
        propertyType: from_candid_PropertyType_n12(_uploadFile, _downloadFile, value.propertyType),
        averagePrice: value.averagePrice,
        pricePerSqm: value.pricePerSqm,
        regionId: value.regionId,
        changePercent: value.changePercent
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region: _Region;
    latestPrice: [] | [_PropertyPrice];
}): {
    region: Region;
    latestPrice?: PropertyPrice;
} {
    return {
        region: from_candid_Region_n17(_uploadFile, _downloadFile, value.region),
        latestPrice: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.latestPrice))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RegionId;
    name: string;
    level: _RegionLevel;
    parentId: [] | [_RegionId];
}): {
    id: RegionId;
    name: string;
    level: RegionLevel;
    parentId?: RegionId;
} {
    return {
        id: value.id,
        name: value.name,
        level: from_candid_RegionLevel_n19(_uploadFile, _downloadFile, value.level),
        parentId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.parentId))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    villa: null;
} | {
    land: null;
} | {
    apartment: null;
}): PropertyType {
    return "villa" in value ? PropertyType.villa : "land" in value ? PropertyType.land : "apartment" in value ? PropertyType.apartment : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    province: null;
} | {
    city: null;
} | {
    district: null;
}): RegionLevel {
    return "province" in value ? RegionLevel.province : "city" in value ? RegionLevel.city : "district" in value ? RegionLevel.district : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RegionSummary>): Array<RegionSummary> {
    return value.map((x)=>from_candid_RegionSummary_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Region>): Array<Region> {
    return value.map((x)=>from_candid_Region_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PropertyPrice>): Array<PropertyPrice> {
    return value.map((x)=>from_candid_PropertyPrice_n10(_uploadFile, _downloadFile, x));
}
function to_candid_PropertyPrice_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyPrice): _PropertyPrice {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_RegionLevel_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegionLevel): _RegionLevel {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Region_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Region): _Region {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegionId | null): [] | [_RegionId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    month: YearMonth;
    changeFromPrevMonth: bigint;
    propertyType: PropertyType;
    averagePrice: bigint;
    pricePerSqm: bigint;
    regionId: RegionId;
    changePercent: bigint;
}): {
    month: _YearMonth;
    changeFromPrevMonth: bigint;
    propertyType: _PropertyType;
    averagePrice: bigint;
    pricePerSqm: bigint;
    regionId: _RegionId;
    changePercent: bigint;
} {
    return {
        month: value.month,
        changeFromPrevMonth: value.changeFromPrevMonth,
        propertyType: to_candid_PropertyType_n3(_uploadFile, _downloadFile, value.propertyType),
        averagePrice: value.averagePrice,
        pricePerSqm: value.pricePerSqm,
        regionId: value.regionId,
        changePercent: value.changePercent
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: RegionId;
    name: string;
    level: RegionLevel;
    parentId?: RegionId;
}): {
    id: _RegionId;
    name: string;
    level: _RegionLevel;
    parentId: [] | [_RegionId];
} {
    return {
        id: value.id,
        name: value.name,
        level: to_candid_RegionLevel_n7(_uploadFile, _downloadFile, value.level),
        parentId: value.parentId ? candid_some(value.parentId) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    villa: null;
} | {
    land: null;
} | {
    apartment: null;
} {
    return value == PropertyType.villa ? {
        villa: null
    } : value == PropertyType.land ? {
        land: null
    } : value == PropertyType.apartment ? {
        apartment: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegionLevel): {
    province: null;
} | {
    city: null;
} | {
    district: null;
} {
    return value == RegionLevel.province ? {
        province: null
    } : value == RegionLevel.city ? {
        city: null
    } : value == RegionLevel.district ? {
        district: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
